Repository salsita/node-pg-migrate, pull requests merged in 2024-08, with the labels that each got.

#1243 fix: treat external connection as open
  src/db.ts
  test/db.spec.ts
Labels: c: bug, p: 1-normal

#1244 release: 7.6.1
  package.json
Labels: c: release

#1021 feat(cli): add tsx support
  .github/workflows/postgres-test.yml
  bin/node-pg-migrate.ts
  package.json
  pnpm-lock.yaml
Labels: c: feature, p: 1-normal

#1261 release: 7.7.0-rc.0
  package.json
Labels: c: release
