Repository salsita/node-pg-migrate, pull requests merged in 2024-07, with the labels that each got.

#1221 docs(readme): better attention of potential contributors
  README.md
Labels: c: docs

#1233 feat: allow specifying SET in createFunction
  src/operations/functions/createFunction.ts
  src/operations/functions/shared.ts
  test/migrations/091_function_set.js
  test/operations/functions/createFunction.spec.ts
Labels: c: feature, p: 1-normal

#1234 chore(deps): update devdependencies (major)
  .eslintrc.cjs
  package.json
  pnpm-lock.yaml
Labels: c: dependencies

#1235 release: 7.6.0
  package.json
Labels: c: release
