Repository salsita/node-pg-migrate, pull requests merged in 2024-04, with the labels that each got.

#1050 test: add materialized views unit tests
  src/operations/viewsMaterialized.ts
  test/operations/materializedViews/alterMaterializedView.spec.ts
  test/operations/materializedViews/createMaterializedView.spec.ts
  test/operations/materializedViews/dropMaterializedView.spec.ts
  test/operations/materializedViews/refreshMaterializedView.spec.ts
  test/operations/materializedViews/renameMaterializedView.spec.ts
  test/operations/materializedViews/renameMaterializedViewColumn.spec.ts
  vitest.config.ts
Labels: c: test, p: 1-normal

#1052 release: 7.0.0-alpha.1
  package.json
Labels: c: release

#1053 chore(utils): restructure utils
  src/utils.ts
  src/utils/StringIdGenerator.ts
  src/utils/createSchemalize.ts
  src/utils/createTransformer.ts
  src/utils/escapeValue.ts
  src/utils/formatLines.ts
  src/utils/formatParams.ts
  src/utils/getMigrationTableSchema.ts
  src/utils/getSchemas.ts
  src/utils/identity.ts
  src/utils/index.ts
  src/utils/intersection.ts
  src/utils/isPgLiteral.ts
  src/utils/makeComment.ts
  src/utils/quote.ts
  src/utils/types.ts
  test/utils.spec.ts
  test/utils/StringIdGenerator.spec.ts
  test/utils/createTransformer.spec.ts
  test/utils/escapeValue.spec.ts
  test/utils/types.spec.ts
Labels: c: chore, p: 1-normal

#1054 chore(utils): improve createTransformer
  src/utils/createTransformer.ts
  test/utils/createTransformer.spec.ts
Labels: c: chore, c: test, p: 1-normal

#1056 test(utils): enhance StringIdGenerator
  src/utils/StringIdGenerator.ts
  test/utils/StringIdGenerator.spec.ts
Labels: c: test, p: 1-normal

#1057 chore(utils): allow immutable in utils types
  src/utils/types.ts
  test/utils/types.spec.ts
Labels: c: chore, c: test, p: 1-normal

#1058 refactor(utils): improve createSchemalize
  src/migration-builder.ts
  src/runner.ts
  src/utils/createSchemalize.ts
  test/presetMigrationOptions.ts
  test/utils/createSchemalize.spec.ts
  test/utils/createTransformer.spec.ts
Labels: c: refactor, c: test

#1059 test(utils): test utils formatLines
  test/utils/formatLines.spec.ts
Labels: c: test, p: 1-normal

#1060 chore(utils): allow immutable in utils format
  src/utils/formatLines.ts
  src/utils/formatParams.ts
  test/utils/formatLines.spec.ts
  test/utils/formatParam.spec.ts
Labels: c: chore, c: test, p: 1-normal

#1061 test(utils): test utils getMigrationTableSchema
  test/utils/getMigrationTableSchema.spec.ts
Labels: c: test, p: 1-normal

#1062 chore(utils): allow immutable in utils getSchema
  src/utils/getSchemas.ts
  test/utils/getSchemas.spec.ts
Labels: c: chore, c: test, p: 1-normal

#1063 chore(utils): add shortcut to isPgLiteral
  src/utils/isPgLiteral.ts
  test/utils/isPgLiteral.spec.ts
Labels: c: chore, c: test, p: 1-normal

#1064 chore(utils): improve makeComment
  src/utils/makeComment.ts
  test/utils/makeComment.spec.ts
Labels: c: chore, c: test, p: 1-normal

#1065 infra: ts-check tests
  test/sqlMigration.spec.ts
  tsconfig.json
  tsconfig.lint.json
Labels: c: infra, p: 1-normal

#1066 chore(cli): cleanup cli
  .eslintrc.cjs
  bin/node-pg-migrate.ts
  package.json
  patches/@types__pg@8.11.4.patch
  pnpm-lock.yaml
  src/migration.ts
  tsconfig.json
Labels: c: chore, p: 1-normal

#1067 release: 7.0.0-alpha.2
  package.json
Labels: c: release

#953 docs(cli): document all possible migration languages
  docs/cli.md
Labels: c: docs

#1068 docs(template): add JSDoc to js migration template
  templates/migration-template.js
Labels: c: docs, p: 1-normal

#1072 refactor(domains): reorganize operations domains
  src/index.ts
  src/operations/domains.ts
  src/operations/domains/alterDomain.ts
  src/operations/domains/createDomain.ts
  src/operations/domains/dropDomain.ts
  src/operations/domains/index.ts
  src/operations/domains/renameDomain.ts
  src/operations/domains/shared.ts
  src/operations/domainsTypes.ts
  src/types.ts
Labels: c: refactor, p: 1-normal

#1074 refactor(functions): reorganize operations functions
  src/index.ts
  src/operations/domains/createDomain.ts
  src/operations/domains/renameDomain.ts
  src/operations/functions.ts
  src/operations/functions/createFunction.ts
  src/operations/functions/dropFunction.ts
  src/operations/functions/index.ts
  src/operations/functions/renameFunction.ts
  src/operations/functions/shared.ts
  src/operations/functionsTypes.ts
  src/operations/operatorsTypes.ts
  src/operations/tables.ts
  src/operations/triggers.ts
  src/operations/triggersTypes.ts
  src/types.ts
  src/utils/formatParams.ts
  src/utils/types.ts
Labels: c: refactor, p: 1-normal

#1075 refactor(indexes): reorganize operations indexes
  src/index.ts
  src/operations/indexes.ts
  src/operations/indexes/createIndex.ts
  src/operations/indexes/dropIndex.ts
  src/operations/indexes/index.ts
  src/operations/indexes/shared.ts
  src/operations/indexesTypes.ts
  src/types.ts
Labels: c: refactor, p: 1-normal

#1076 refactor(policies): reorganize operations policies
  src/index.ts
  src/operations/policies.ts
  src/operations/policies/alterPolicy.ts
  src/operations/policies/createPolicy.ts
  src/operations/policies/dropPolicy.ts
  src/operations/policies/index.ts
  src/operations/policies/renamePolicy.ts
  src/operations/policies/shared.ts
  src/operations/policiesTypes.ts
  src/types.ts
Labels: c: refactor, p: 1-normal

#1077 refactor(operators): reorganize operations operators
  src/index.ts
  src/operations/operators.ts
  src/operations/operators/addToOperatorFamily.ts
  src/operations/operators/createOperator.ts
  src/operations/operators/createOperatorClass.ts
  src/operations/operators/createOperatorFamily.ts
  src/operations/operators/dropOperator.ts
  src/operations/operators/dropOperatorClass.ts
  src/operations/operators/dropOperatorFamily.ts
  src/operations/operators/index.ts
  src/operations/operators/removeFromOperatorFamily.ts
  src/operations/operators/renameOperatorClass.ts
  src/operations/operators/renameOperatorFamily.ts
  src/operations/operators/shared.ts
  src/operations/operatorsTypes.ts
  src/types.ts
Labels: c: refactor, p: 1-normal

#1078 refactor(sql): reorganize operations sql
  src/index.ts
  src/migration-builder.ts
  src/operations/othersTypes.ts
  src/operations/sql.ts
  src/types.ts
  test/operations/sql.spec.ts
Labels: c: refactor, p: 1-normal

#1079 refactor(roles): reorganize operations roles
  src/index.ts
  src/operations/roles.ts
  src/operations/roles/alterRole.ts
  src/operations/roles/createRole.ts
  src/operations/roles/dropRole.ts
  src/operations/roles/index.ts
  src/operations/roles/renameRole.ts
  src/operations/roles/shared.ts
  src/operations/rolesTypes.ts
  src/types.ts
Labels: c: refactor, p: 1-normal

#1080 refactor(schemas): reorganize operations schemas
  src/index.ts
  src/operations/schemas.ts
  src/operations/schemas/createSchema.ts
  src/operations/schemas/dropSchema.ts
  src/operations/schemas/index.ts
  src/operations/schemas/renameSchema.ts
  src/operations/schemasTypes.ts
  src/types.ts
Labels: c: refactor, p: 1-normal

#1081 refactor(sequences): reorganize operations sequences
  src/index.ts
  src/operations/sequences.ts
  src/operations/sequences/alterSequence.ts
  src/operations/sequences/createSequence.ts
  src/operations/sequences/dropSequence.ts
  src/operations/sequences/index.ts
  src/operations/sequences/renameSequence.ts
  src/operations/sequences/shared.ts
  src/operations/sequencesTypes.ts
  src/operations/tablesTypes.ts
  src/types.ts
Labels: c: refactor, p: 1-normal

#1083 refactor(triggers): reorganize operations triggers
  src/index.ts
  src/operations/triggers/createTrigger.ts
  src/operations/triggers/dropTrigger.ts
  src/operations/triggers/index.ts
  src/operations/triggers/renameTrigger.ts
  src/operations/triggers/shared.ts
  src/operations/triggersTypes.ts
  src/types.ts
Labels: c: refactor, p: 1-normal

#1084 refactor(types): reorganize operations types
  src/index.ts
  src/operations/types.ts
  src/operations/types/addTypeAttribute.ts
  src/operations/types/addTypeValue.ts
  src/operations/types/createType.ts
  src/operations/types/dropType.ts
  src/operations/types/dropTypeAttribute.ts
  src/operations/types/index.ts
  src/operations/types/renameType.ts
  src/operations/types/renameTypeAttribute.ts
  src/operations/types/renameTypeValue.ts
  src/operations/types/setTypeAttribute.ts
  src/operations/typesTypes.ts
  src/types.ts
Labels: c: refactor, p: 1-normal

#1085 refactor(views): reorganize operations views
  src/index.ts
  src/operations/views.ts
  src/operations/views/alterView.ts
  src/operations/views/alterViewColumn.ts
  src/operations/views/createView.ts
  src/operations/views/dropView.ts
  src/operations/views/index.ts
  src/operations/views/renameView.ts
  src/operations/views/shared.ts
  src/operations/viewsTypes.ts
  src/types.ts
Labels: c: refactor, p: 1-normal

#1086 refactor(mViews): reorganize operations materialized views
  src/index.ts
  src/migration-builder.ts
  src/operations/materializedViews/alterMaterializedView.ts
  src/operations/materializedViews/createMaterializedView.ts
  src/operations/materializedViews/dropMaterializedView.ts
  src/operations/materializedViews/index.ts
  src/operations/materializedViews/refreshMaterializedView.ts
  src/operations/materializedViews/renameMaterializedView.ts
  src/operations/materializedViews/renameMaterializedViewColumn.ts
  src/operations/materializedViews/shared.ts
  src/operations/viewsMaterialized.ts
  src/operations/viewsMaterializedTypes.ts
  src/types.ts
  test/operations/materializedViews/alterMaterializedView.spec.ts
  test/operations/materializedViews/createMaterializedView.spec.ts
  test/operations/materializedViews/dropMaterializedView.spec.ts
  test/operations/materializedViews/refreshMaterializedView.spec.ts
  test/operations/materializedViews/renameMaterializedView.spec.ts
  test/operations/materializedViews/renameMaterializedViewColumn.spec.ts
Labels: c: refactor, p: 1-normal

#1087 refactor(pgLiteral): reorganize utils PgLiteral
  src/index.ts
  src/migration-builder.ts
  src/operations/PgLiteral.ts
  src/operations/generalTypes.ts
  src/types.ts
  src/utils/PgLiteral.ts
  src/utils/index.ts
  src/utils/isPgLiteral.ts
Labels: c: refactor, p: 1-normal

#929 feat: accept ts-node tsconfig overrides
  bin/node-pg-migrate.ts
Labels: c: feature

#1090 release: 7.0.0-alpha.3
  package.json
Labels: c: release

#1094 fix(constraint)!: throw error on string expression
  src/operations/tables/addConstraint.ts
  test/operations/constraints/addConstraint.spec.ts
Labels: c: bug, p: 1-normal

#1095 chore: add Reversible type
  src/index.ts
  src/migration-builder.ts
  src/operations/domains/createDomain.ts
  src/operations/domains/renameDomain.ts
  src/operations/extensions/createExtension.ts
  src/operations/functions/createFunction.ts
  src/operations/functions/renameFunction.ts
  src/operations/generalTypes.ts
  src/operations/indexes/createIndex.ts
  src/operations/materializedViews/createMaterializedView.ts
  src/operations/materializedViews/refreshMaterializedView.ts
  src/operations/materializedViews/renameMaterializedView.ts
  src/operations/materializedViews/renameMaterializedViewColumn.ts
  src/operations/operators/addToOperatorFamily.ts
  src/operations/operators/createOperator.ts
  src/operations/operators/createOperatorClass.ts
  src/operations/operators/createOperatorFamily.ts
  src/operations/operators/renameOperatorClass.ts
  src/operations/operators/renameOperatorFamily.ts
  src/operations/policies/createPolicy.ts
  src/operations/policies/renamePolicy.ts
  src/operations/roles/createRole.ts
  src/operations/roles/renameRole.ts
  src/operations/schemas/createSchema.ts
  src/operations/schemas/renameSchema.ts
  src/operations/sequences/createSequence.ts
  src/operations/sequences/renameSequence.ts
  src/operations/tables/addColumns.ts
  src/operations/tables/addConstraint.ts
  src/operations/tables/createTable.ts
  src/operations/tables/renameColumn.ts
  src/operations/tables/renameConstraint.ts
  src/operations/tables/renameTable.ts
  src/operations/triggers/createTrigger.ts
  src/operations/triggers/renameTrigger.ts
  src/operations/types/addTypeAttribute.ts
  src/operations/types/createType.ts
  src/operations/types/renameType.ts
  src/operations/types/renameTypeAttribute.ts
  src/operations/types/renameTypeValue.ts
  src/operations/views/createView.ts
  src/operations/views/renameView.ts
Labels: c: chore, p: 1-normal

#1099 refactor(deps): inline decamelize dependency
  package.json
  pnpm-lock.yaml
  src/utils/createSchemalize.ts
  src/utils/decamelize.ts
  src/utils/index.ts
  test/utils/decamelize.spec.ts
Labels: c: dependencies, c: refactor, p: 1-normal

#1101 refactor!: refactor base files
  src/db.ts
  src/migration.ts
  src/migrationBuilder.ts
  src/runner.ts
  src/sqlMigration.ts
  test/ts/customRunner.ts
Labels: breaking change, c: refactor, p: 1-normal

#1102 refactor: use native mkdir recursive
  package.json
  pnpm-lock.yaml
  src/migration.ts
Labels: c: dependencies, c: refactor, p: 1-normal

#1103 docs: update README.md
  README.md
Labels: c: docs, p: 1-normal

#1104 docs: add JSDoc for pgm
  src/types.ts
Labels: c: docs, p: 1-normal

#1106 release: 7.0.0-alpha.4
  package.json
Labels: c: release, p: 1-normal

#1107 docs: update doc website
  docs/README.md
  docs/api.md
  docs/cli.md
  docs/transpiling.md
Labels: c: docs, p: 1-normal

#1108 release: 7.0.0
  package.json
  pnpm-lock.yaml
Labels: c: release

#1111 docs: add note/link to changelog
  CHANGELOG.md
Labels: c: docs, p: 1-normal

#1113 release: 7.1.0
  package.json
Labels: c: release

#942 feat(casts): support create and drop cast
  docs/README.md
  docs/_sidebar.md
  docs/casts.md
  src/index.ts
  src/migrationBuilder.ts
  src/operations/casts/createCast.ts
  src/operations/casts/dropCast.ts
  src/operations/casts/index.ts
  src/types.ts
  test/migrations/090_create_cast.js
  test/operations/casts/createCast.spec.ts
  test/operations/casts/dropCast.spec.ts
Labels: c: feature, p: 1-normal

#1114 ci: update cockroach
  .github/workflows/cockroach-test.yml
Labels: c: infra, p: 1-normal

#1118 release: 7.2.0
  package.json
Labels: c: release

#1123 chore(deps): upgrade eslint to v9
  package.json
  pnpm-lock.yaml
Labels: c: dependencies

#1124 chore(deps): upgrade dotenv-expand to v11
  package.json
  pnpm-lock.yaml
Labels: c: dependencies

#1126 ci: fix coverage workflow
  .github/workflows/coverage.yml
Labels: c: infra, p: 1-normal

#1129 refactor: unify codestyle
  src/index.ts
  src/operations/casts/createCast.ts
  src/operations/casts/dropCast.ts
  src/operations/domains/alterDomain.ts
  src/operations/domains/createDomain.ts
  src/operations/domains/dropDomain.ts
  src/operations/extensions/createExtension.ts
  src/operations/extensions/dropExtension.ts
  src/operations/functions/createFunction.ts
  src/operations/functions/dropFunction.ts
  src/operations/grants/grantOnSchemas.ts
  src/operations/grants/grantOnTables.ts
  src/operations/grants/grantRoles.ts
  src/operations/grants/revokeOnSchemas.ts
  src/operations/grants/revokeOnTables.ts
  src/operations/grants/revokeRoles.ts
  src/operations/indexes/createIndex.ts
  src/operations/indexes/dropIndex.ts
  src/operations/materializedViews/alterMaterializedView.ts
  src/operations/materializedViews/createMaterializedView.ts
  src/operations/materializedViews/dropMaterializedView.ts
  src/operations/materializedViews/refreshMaterializedView.ts
  src/operations/operators/createOperator.ts
  src/operations/operators/createOperatorClass.ts
  src/operations/operators/createOperatorFamily.ts
  src/operations/operators/dropOperator.ts
  src/operations/operators/dropOperatorClass.ts
  src/operations/operators/dropOperatorFamily.ts
  src/operations/policies/alterPolicy.ts
  src/operations/policies/createPolicy.ts
  src/operations/policies/dropPolicy.ts
  src/operations/roles/createRole.ts
  src/operations/roles/dropRole.ts
  src/operations/schemas/createSchema.ts
  src/operations/schemas/dropSchema.ts
  src/operations/sequences/alterSequence.ts
  src/operations/sequences/createSequence.ts
  src/operations/sequences/dropSequence.ts
  src/operations/tables/addColumns.ts
  src/operations/tables/addConstraint.ts
  src/operations/tables/alterTable.ts
  src/operations/tables/createTable.ts
  src/operations/tables/dropColumns.ts
  src/operations/tables/dropConstraint.ts
  src/operations/tables/dropTable.ts
  src/operations/triggers/createTrigger.ts
  src/operations/triggers/dropTrigger.ts
  src/operations/types/addTypeAttribute.ts
  src/operations/types/addTypeValue.ts
  src/operations/types/createType.ts
  src/operations/types/dropType.ts
  src/operations/types/dropTypeAttribute.ts
  src/operations/views/alterView.ts
  src/operations/views/alterViewColumn.ts
  src/operations/views/createView.ts
  src/operations/views/dropView.ts
  test/operations/constraints/addConstraint.spec.ts
Labels: c: refactor, p: 1-normal

#1130 refactor: unify codestyle
  src/db.ts
  src/migration.ts
  src/runner.ts
  src/sqlMigration.ts
  test/migrations/005_table_test.js
  test/migrations/022_add_type_test.js
  test/migrations/024_add_type_attribute_test.js
  test/migrations/026_set_type_attribute_test.js
  test/migrations/030_rename_type_attribute_test.js
  test/migrations/032_drop_type_attribute_test.js
  test/migrations/041_function_test.js
  test/migrations/055_operator_test.js
  test/operations/functions/createFunction.spec.ts
  test/runner.spec.ts
Labels: c: refactor, p: 1-normal

#1131 refactor: configure eslint unicorn
  .eslintrc.cjs
  bin/node-pg-migrate.ts
  package.json
  pnpm-lock.yaml
  src/db.ts
  src/index.ts
  src/migration.ts
  src/migrationBuilder.ts
  src/operations/domains/createDomain.ts
  src/operations/indexes/shared.ts
  src/operations/materializedViews/shared.ts
  src/operations/tables/alterColumn.ts
  src/operations/tables/createTable.ts
  src/operations/tables/shared.ts
  src/runner.ts
  src/sqlMigration.ts
  src/utils/getMigrationTableSchema.ts
  src/utils/toArray.ts
  test/migration.spec.ts
  test/migrations/005_table_test.js
  test/migrations/010_column_test.js
  test/migrations/013_column_alter_test.js
  test/migrations/015_add_constraint_test.js
  test/migrations/026_set_type_attribute_test.js
  test/migrations/032_drop_type_attribute_test.js
  test/migrations/034_drop_type_test.js
  test/migrations/047_domain_check.js
  test/migrations/081_temporary_table.js
  test/migrations/086_grant_test.js
  test/ts/customRunner.ts
  test/ts/customRunnerDBClient.ts
  test/ts/customRunnerDBUrl.ts
  test/ts/customRunnerUndefCount.ts
  test/utils/StringIdGenerator.spec.ts
Labels: c: dependencies, c: refactor, p: 1-normal

#1119 fix: restore support url as an object in configuration
  .github/workflows/postgres-test.yml
  bin/node-pg-migrate.ts
Labels: c: bug, p: 1-normal

#1132 docs: refactor docs to use VitePress
  .github/workflows/docs.yml
  docs/.nojekyll
  docs/.vitepress/config.mts
  docs/.vitepress/theme/index.ts
  docs/.vitepress/theme/style.css
  docs/README.md
  docs/_sidebar.md
  docs/api.md
  docs/casts.md
  docs/cli.md
  docs/columns.md
  docs/constraints.md
  docs/domains.md
  docs/extensions.md
  docs/index.html
  docs/migrations.md
  docs/misc.md
  docs/src/api.md
  docs/src/cli.md
  docs/src/faq/transpiling.md
  docs/src/faq/troubleshooting.md
  docs/src/getting-started.md
  docs/src/index.md
  docs/src/introduction.md
  docs/src/migrations/casts.md
  docs/src/migrations/columns.md
  docs/src/migrations/constraints.md
  docs/src/migrations/domains.md
  docs/src/migrations/extensions.md
  docs/src/migrations/functions.md
  docs/src/migrations/grants.md
  docs/src/migrations/index.md
  docs/src/migrations/indexes.md
  docs/src/migrations/mViews.md
  docs/src/migrations/misc.md
  docs/src/migrations/operators.md
  docs/src/migrations/policies.md
  docs/src/migrations/roles.md
  docs/src/migrations/schemas.md
  docs/src/migrations/sequences.md
  docs/src/migrations/tables.md
  docs/src/migrations/triggers.md
  docs/src/migrations/types.md
  docs/src/migrations/views.md
  docs/transpiling.md
  docs/triggers.md
  package.json
  pnpm-lock.yaml
  tsconfig.json
Labels: c: docs, p: 1-normal

#1135 chore(deps): lock file maintenance
  package.json
  pnpm-lock.yaml
Labels: c: dependencies

#1136 release: 7.2.1
  package.json
Labels: c: release
