Repository salsita/node-pg-migrate, pull requests merged in 2024-06, with the labels that each got.

#1191 fix(columns): handle column with cascade option in dropColumns
  src/operations/tables/dropColumns.ts
  test/operations/columns/dropColumns.spec.ts
Labels: c: bug, p: 1-normal

#1197 infra: pnpm v9.2 fixed strictness
  .npmrc
Labels: c: infra

#1187 fix: use createRequire to support esm
  bin/node-pg-migrate.ts
  package.json
  pnpm-lock.yaml
  src/migration.ts
  tsconfig.json
  tsup-bin.config.ts
  tsup.config.ts
Labels: c: bug

#1205 release: 7.5.0
  package.json
Labels: c: release

#1208 fix(esm): dont depend on `__dirname`
  bin/node-pg-migrate.ts
  src/migration.ts
  src/runner.ts
Labels: c: bug

#1209 fix(esm): fix `pg` import
  src/db.ts
  test/db.spec.ts
Labels: c: bug

#1212 release: 7.5.1
  package.json
Labels: c: release

#1215 chore: use node:process cwd
  bin/node-pg-migrate.ts
  src/migration.ts
Labels: c: chore, p: 1-normal

#1216 fix(cli): correctly validate schema
  bin/node-pg-migrate.ts
Labels: c: bug, p: 1-normal

#1217 release: 7.5.2
  package.json
Labels: c: release
