Repository salsita/node-pg-migrate, pull requests merged in 2024-05, with the labels that each got.

#1139 fix: correctly pass table with schema when using comment
  src/operations/tables/shared.ts
  test/migrations/014_add_constraint.js
Labels: c: bug, c: test, p: 1-normal

#1143 release: 7.2.2
  package.json
Labels: c: release

#1144 chore(deps): downgrade eslint to v8
  package.json
  pnpm-lock.yaml
Labels: c: dependencies

#1148 fix: fix esm
  .gitignore
  bin/node-pg-migrate.ts
  package.json
  pnpm-lock.yaml
  src/db.ts
  tsup-bin.config.ts
  tsup.config.ts
Labels: c: bug, p: 2-high

#1157 release: 7.3.0
  package.json
Labels: c: release

#1155 fix: use union type in addConstraint
  src/index.ts
  src/operations/tables/addConstraint.ts
  test/operations/constraints/addConstraint.spec.ts
Labels: c: bug, p: 1-normal

#1161 release: 7.3.2
  package.json
Labels: c: release

#1162 docs: refactor migration operations
  docs/src/migrations/functions.md
  docs/src/migrations/grants.md
  docs/src/migrations/indexes.md
  docs/src/migrations/mViews.md
  docs/src/migrations/operators.md
  docs/src/migrations/policies.md
  docs/src/migrations/roles.md
  docs/src/migrations/schemas.md
  docs/src/migrations/sequences.md
  docs/src/migrations/tables.md
  docs/src/migrations/types.md
  docs/src/migrations/views.md
Labels: c: docs

#1176 feat(functions): support security
  docs/src/migrations/functions.md
  src/operations/functions/createFunction.ts
  src/operations/functions/shared.ts
  test/migrations/039_function_create.js
  test/operations/functions/createFunction.spec.ts
Labels: c: feature, p: 1-normal

#1177 release: 7.4.0
  package.json
Labels: c: release
