Repository salsita/node-pg-migrate, pull requests merged in 2025-07, with the labels that each got.

#1466 test: remove outdated TODO comment in `createTable` spec
  test/operations/tables/createTable.spec.ts
Labels: breaking change, c: refactor

#1460 feat!: jiti support
  .github/workflows/postgres-test.yml
  bin/node-pg-migrate.ts
  docs/.vitepress/config.mts
  docs/src/cli.md
  docs/src/faq/transpiling.md
  docs/src/faq/troubleshooting.md
  docs/src/faq/typescript.md
  docs/src/getting-started.md
  eslint.config.ts
  package.json
  pnpm-lock.yaml
  src/runner.ts
  test/jiti/jiti.spec.ts
  test/jiti/migrations/1-test-migration.js
  test/jiti/migrations/1-test-migration.mjs
  test/jiti/migrations/1-test-migration.mts
  test/jiti/migrations/1-test-migration.ts
Labels: breaking change, c: feature

#1462 fix!: throw error when no constraint options are provided in addConstraint
  src/operations/tables/addConstraint.ts
  test/operations/constraints/addConstraint.spec.ts
Labels: breaking change, c: refactor

#1463 fix!: throw error when no policy options are provided in alterPolicy
  src/operations/policies/alterPolicy.ts
  test/operations/policies/alterPolicy.spec.ts
Labels: breaking change, c: refactor

#1464 fix!: throw error when no sequence options are provided in alterSequence
  src/operations/sequences/alterSequence.ts
  test/operations/sequences/alterSequence.spec.ts
Labels: breaking change, c: refactor

#1465 fix!: throw error when no options are provided in alterTable
  src/operations/tables/alterTable.ts
  test/operations/tables/alterTable.spec.ts
Labels: breaking change, c: refactor

#1479 release: 9.0.0-alpha.0
  package.json
Labels: c: release
