Repository salsita/node-pg-migrate, pull requests merged in 2025-01, with the labels that each got.

#1305 feat: alterColumn with expressionGenerated
  src/operations/tables/alterColumn.ts
  test/migration.spec.ts
  test/migrations/093_alter_column_expression.js
  test/operations/columns/alterColumn.spec.ts
Labels: c: feature, p: 1-normal

#1306 chore: update license year
  LICENSE
Labels: c: chore

#1307 infra: add prettier-plugin-packagejson
  .prettierrc.js
  package.json
  pnpm-lock.yaml
Labels: c: dependencies, c: infra

#1308 chore(deps): upgrade eslint v9
  .eslintrc.cjs
  eslint.config.ts
  package.json
  pnpm-lock.yaml
  src/operations/operators/createOperatorFamily.ts
  test/db.spec.ts
  test/migration.spec.ts
  test/runner.spec.ts
Labels: c: dependencies, c: chore

#1311 release: 7.9.0
  package.json
Labels: c: release

#1312 infra: update integration test dbs
  .github/workflows/cockroach-test.yml
  .github/workflows/postgres-test.yml
  test/migrations/093_alter_column_expression.js
Labels: c: infra
