Repository salsita/node-pg-migrate, pull requests merged in 2025-02, with the labels that each got.

#1327 release: 7.9.1
  package.json
Labels: c: release

#1264 chore!: drop node v18 support
  .github/workflows/ci.yml
  .github/workflows/postgres-test.yml
  README.md
  docs/src/getting-started.md
  package.json
  pnpm-lock.yaml
  tsconfig.json
  tsconfig.lint.json
  tsup-bin.config.ts
  tsup.config.ts
Labels: c: dependencies, breaking change, c: refactor, p: 1-normal

#1333 fix: template resolution for monorepos
  src/migration.ts
Labels: c: bug

#1334 docs: update introduction
  README.md
  docs/src/getting-started.md
  docs/src/introduction.md
Labels: c: docs

#1335 release: 8.0.0-rc.0
  package.json
Labels: c: release

#1340 refactor!: remove deprecations
  src/operations/indexes/createIndex.ts
  src/operations/tables/alterColumn.ts
  src/operations/tables/shared.ts
  src/utils/createSchemalize.ts
  test/migrations/077_create_table_generated_column.js
  test/operations/indexes/createIndex.spec.ts
  test/utils/createSchemalize.spec.ts
Labels: breaking change, c: refactor, p: 1-normal

#1341 chore: convert ConnectionStatus enum to native
  src/db.ts
Labels: c: chore, p: 1-normal

#1342 infra(deps): disable major node types
  .github/renovate.json5
Labels: c: infra

#1343 chore: convert FilenameFormat enum to native
  bin/node-pg-migrate.ts
  src/migration.ts
Labels: c: chore, p: 1-normal

#1344 chore: convert PgType enum to native
  src/types.ts
Labels: c: chore, p: 1-normal

#1345 infra: broaden integration-test ranges
  .github/workflows/cockroach-test.yml
  .github/workflows/postgres-test.yml
Labels: c: infra, c: test, p: 1-normal

#1347 release: 8.0.0-rc.1
  package.json
  pnpm-lock.yaml
Labels: c: release

#1346 feat: expose enableReverseMode from migrator
  src/types.ts
  test/1739900132875_names_reversed.js
  test/migration.spec.ts
Labels: c: feature, p: 1-normal, s: accepted

#1348 refactor!: checkOrder by default
  src/runner.ts
Labels: breaking change, c: refactor, p: 1-normal

#1349 refactor: improve PgType
  src/types.ts
Labels: c: docs, c: refactor, p: 1-normal

#1350 chore: remove typescript sugar from constructors
  src/utils/PgLiteral.ts
  src/utils/StringIdGenerator.ts
Labels: c: chore, p: 1-normal

#1352 refactor!: remove default exports
  bin/node-pg-migrate.ts
  src/db.ts
  src/index.ts
  src/migration.ts
  src/migrationBuilder.ts
  src/runner.ts
  src/sqlMigration.ts
  test/db.spec.ts
Labels: breaking change, c: refactor, p: 1-normal

#1353 release: v8.0.0-rc.2
  package.json
  pnpm-lock.yaml
Labels: c: release
