Repository salsita/node-pg-migrate, pull requests merged in 2025-06, with the labels that each got.

#1425 docs: update path for ts-node migration script in transpiling.md
  docs/src/faq/transpiling.md
Labels: c: docs

#1437 fix: switches moduleResolution to Bundler and build .d.ts files with tsup
  .github/workflows/ci.yml
  bin/node-pg-migrate.ts
  package.json
  pnpm-lock.yaml
  src/index.ts
  src/migration.ts
  src/migrationBuilder.ts
  test/ts/customRunner.ts
  test/ts/migrations/1-test-migration.ts
  test/ts/migrations/2-test-migration.ts
  tsconfig.build.json
  tsconfig.json
  tsconfig.lint.json
  tsup-bin.config.ts
  tsup.config.ts
Labels: c: bug

#1452 infra: utilize git clean
  package.json
  pnpm-lock.yaml
Labels: c: infra
