Repository salsita/node-pg-migrate, pull requests merged in 2025-05, with the labels that each got.

#1401 chore: upgrade node
  .github/workflows/ci.yml
  .github/workflows/cockroach-test.yml
  .github/workflows/coverage.yml
  .github/workflows/docs.yml
  .github/workflows/postgres-test.yml
  .github/workflows/publish.yml
  eslint.config.ts
Labels: c: infra

#1405 feat: add UNLOGGED support for table
  docs/src/migrations/tables.md
  src/operations/tables/alterTable.ts
  src/operations/tables/createTable.ts
  src/operations/tables/shared.ts
  test/migration.spec.ts
  test/migrations/094_unlogged_table.js
  test/operations/tables/alterTable.spec.ts
  test/operations/tables/createTable.spec.ts
Labels: c: feature, p: 1-normal

#1403 feat: add customizable lock value
  bin/node-pg-migrate.ts
  docs/src/api.md
  src/index.ts
  src/runner.ts
  test/runner.spec.ts
Labels: c: feature, p: 1-normal

#1409 release: 8.0.0-rc.6
  package.json
Labels: c: release

#1414 release: 8.0.0
  package.json
Labels: c: release

#1421 release: 8.0.1
  package.json
Labels: c: release
