Repository salsita/node-pg-migrate, pull requests merged in 2025-03, with the labels that each got.

#1363 chore: enable erasableSyntaxOnly
  tsconfig.json
  tsconfig.lint.json
  vitest.config.ts
Labels: c: chore, p: 1-normal

#1364 test: suppress warning
  test/migration.spec.ts
Labels: c: test, p: 1-normal

#1285 feat: expose MigrationBuilder to allow using as sql builder
  src/index.ts
  test/__snapshots__/migrationBuilder.spec.ts.snap
  test/migrationBuilder.spec.ts
Labels: c: feature, p: 1-normal

#1365 fix!: throw error on missing db option
  src/runner.ts
  test/runner.spec.ts
Labels: breaking change

#1377 release: 8.0.0-rc.4
  package.json
  pnpm-lock.yaml
Labels: c: release
