Repository salsita/node-pg-migrate, pull requests merged in 2025-04, with the labels that each got.

#1385 chore(deps): remove eslint-define-config
  package.json
  pnpm-lock.yaml
Labels: dependencies

#1222 fix(cli)!: ensure env vars are set before migrating
  .github/workflows/postgres-test.yml
  bin/node-pg-migrate.ts
  docs/src/faq/troubleshooting.md
Labels: breaking change, c: bug, p: 1-normal

#1389 chore: use eslint defineConfig
  eslint.config.ts
  package.json
  pnpm-lock.yaml
Labels: c: chore, p: 1-normal
